name       : burn-my-windows
version    : 32
release    : 1
source     :
    - https://github.com/Schneegans/Burn-My-Windows/archive/refs/tags/v32.tar.gz : 5ab244212660dfdb4ce470a3e1f5eafdf377e9325aa67bb4218b3651cf334ac2
homepage   : https://github.com/Schneegans/Burn-My-Windows
license    : GPL-3.0-or-later
component  :
    - ^gnome-shell-extension-burn-my-windows: desktop.gnome
    - ^kwin-effects-burn-my-windows: desktop.gnome
summary    :
    - Disintegrate your windows with style
    - ^gnome-shell-extension-burn-my-windows: Disintegrate your windows with style - GNOME
    - ^kwin-effects-burn-my-windows: Disintegrate your windows with style - Plasma
description:
    - Disintegrate your windows with style
    - ^gnome-shell-extension-burn-my-windows: Disintegrate your windows with style - GNOME
    - ^kwin-effects-burn-my-windows: Disintegrate your windows with style - Plasma
build      : |
    make zip

    pushd kwin
    ./build.sh
    popd
install    : |
    export UUID=$(grep -Po '(?<="uuid": ")[^"]*' metadata.json)
    install -d $installdir/usr/share/gnome-shell/extensions/${UUID}
    bsdtar -xvf ${UUID}.zip -C $installdir/usr/share/gnome-shell/extensions/${UUID}

    mkdir -p $installdir/usr/share/kwin/effects/
    cp -r kwin/_build/. $installdir/usr/share/kwin/effects
patterns   :
    - ^gnome-shell-extension-burn-my-windows:
        - /usr/share/gnome-shell/
    - ^kwin-effects-burn-my-windows:
        - /usr/share/kwin/
